name: chatable
description: "Chatable is an open source cross-platform table-data easy processing software written in Flutter and Rust."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  chatable_lib:
    path: rust_builder
  flutter_rust_bridge: 2.9.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  window_manager: ^0.4.3
  fluent_ui: ^4.11.2
  package_info_plus: ^8.0.1
  path_provider: ^2.1.5
  path: 1.9.1
  get: ^4.6.6
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  event_bus: ^2.0.1
  multi_column_list_view: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  generate: true
