name: chatable
description: "Chatable is an open source cross-platform table-data easy processing software written in Flutter and Rust."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  chatable_lib:
    path: rust_builder
  flutter_rust_bridge: 2.9.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  generate: true
